//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRS_Admin_client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBRSEntities : DbContext
    {
        public dbBRSEntities()
            : base("name=dbBRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tableAdmins> tableAdmins { get; set; }
        public DbSet<tableBalli> tableBalli { get; set; }
        public DbSet<tableDisciplin> tableDisciplin { get; set; }
        public DbSet<tableFacultet> tableFacultet { get; set; }
        public DbSet<tableGrupp> tableGrupp { get; set; }
        public DbSet<tablePoseshenie> tablePoseshenie { get; set; }
        public DbSet<tablePrepods> tablePrepods { get; set; }
        public DbSet<tablePrinadlegnistDisciplin> tablePrinadlegnistDisciplin { get; set; }
        public DbSet<tableRoles> tableRoles { get; set; }
        public DbSet<tableStudents> tableStudents { get; set; }
        public DbSet<tableZanyatiy> tableZanyatiy { get; set; }
        public DbSet<teachersAccounts> teachersAccounts { get; set; }
        public DbSet<tableProfile> tableProfile { get; set; }
    }
}
