//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRS_Admin_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablePoseshenie
    {
        public int ID { get; set; }
        public int ID_Studenta { get; set; }
        public int ID_Zanyatiya { get; set; }
        public byte Otmetka { get; set; }
    
        public virtual tableStudents tableStudents { get; set; }
        public virtual tableZanyatiy tableZanyatiy { get; set; }
    }
}
