//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRSGSTOU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableStudents
    {
        public tableStudents()
        {
            this.tableBalli = new HashSet<tableBalli>();
            this.tablePoseshenie = new HashSet<tablePoseshenie>();
        }
    
        public int ID { get; set; }
        public int ID_Gruppi { get; set; }
        public string NomerZachetki { get; set; }
        public string Name { get; set; }
        public byte DopuskKSessii { get; set; }
    
        public virtual ICollection<tableBalli> tableBalli { get; set; }
        public virtual tableGrupp tableGrupp { get; set; }
        public virtual ICollection<tablePoseshenie> tablePoseshenie { get; set; }
    }
}
