//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRSGSTOU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableZanyatiy
    {
        public tableZanyatiy()
        {
            this.tablePoseshenie = new HashSet<tablePoseshenie>();
        }
    
        public int ID { get; set; }
        public int ID_Gruppi { get; set; }
        public int ID_Disciplini { get; set; }
        public int ID_Prepoda { get; set; }
        public System.DateTime Vremya { get; set; }
    
        public virtual tableDisciplin tableDisciplin { get; set; }
        public virtual tableGrupp tableGrupp { get; set; }
        public virtual ICollection<tablePoseshenie> tablePoseshenie { get; set; }
        public virtual tablePrepods tablePrepods { get; set; }
    }
}
