//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRSGSTOU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachersAccounts
    {
        public int ID { get; set; }
        public int Role_ID { get; set; }
        public int ID_Prepoda { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual tablePrepods tablePrepods { get; set; }
        public virtual tableRoles tableRoles { get; set; }
    }
}
